server:
  port: 9009
spring:
  application:
    name: tensqure_sms
  rabbitmq:
    host: 192.168.200.68
aliyun:
  sms:
    accessKeyId: LTAIm84IKu87WWqg
    accessKeySecret: zcrdRYvJ2vWfDYdf6Z5MXG7ypyHH1X
    template_code: SMS_137670376
    sign_name: Tree
